---
name: Build and Publish Docker imgadm

on:
  push:
    branches: [ main ]

jobs:
  check:
    name: Check changed files
    outputs:
      # echo_service: ${{ steps.check_files.outputs.echo_service }}
      echo_service: 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: check modified files
        id: check_files
        # run: |
        #     echo "=============== list modified files ==============="
        #     git diff --name-only HEAD^ HEAD
        #     echo "========== check paths of modified files =========="
        #     git diff --name-only HEAD^ HEAD > files.txt
        #     while IFS= read -r file; do
        #       echo $file
        #       if [[ $file == echo_service/* ]]; then
        #         echo "::set-output name=echo_service::true"
        #         echo "file does not belong to any service"
        #       fi
        #     done < files.txt
  echo_service:
    needs: check
    if: needs.check.outputs.echo_service == 'true'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Publish to Registry
      uses: docker/build-push-action@v2
      with:
        context: echo_service/
        push: true
        tags: fofonovrv/echo_service:latest

    - name: Deploy Service
      uses: dawidd6/action-ansible-playbook@v2
      with:
        playbook: deploy.yml
        directory: echo_service/
        key: ${{secrets.SSH_PRIV_KEY}}
        inventory: |
          [all]
          test-host ansible_host=${{secrets.ANSIBLE_HOST}} ansible_ssh_user=${{secrets.ANSIBLE_USER}} 
        options: |
          --verbose